### ISSUE TITLE
Joining an existing BG [$10 awarded]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/mod-cfbg#11]
Sometimes new Battlegrounds start even if there are already other Battlegrounds that have free slots.

Happens mostly when a lot of players queued at the same time (for example when a BG just finished).

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/mod-cfbg/blob/master/src/CFBG.cpp#L373 can be related? Difference of 1 or more.

**Comment by IceNet** [comment]
Confirmed

Sometimes a new BG is opening. So we have 2 open BG with 4-5 players inside.

**Comment by BarbzYHOOL** [comment]
nefertum, you're talking about the `>1` to change into `>=1` ?

**Comment by Nefertumm** [comment]
Perhaps, i'm not 100% sure

**Comment by BarbzYHOOL** [comment]
try it shin !

**Comment by Helias** [comment]
Excellent! a bounty of **10$** :moneybag:  has beend placed here!

**Comment by FrancescoBorzi** [comment]
I've updated the original issue with basically what IceNet said, which was the main problem here:

> Confirmed
> Sometimes a new BG is opening. So we have 2 open BG with 4-5 players inside.

(the issue I've originally described, which I thought was just the root cause of the main problem, I was no longer able to reproduce, so maybe it was just my mistake back then).

I've realised that the main problem was a core issue, here's the fix:

https://github.com/azerothcore/azerothcore-wotlk/pull/3082

@IceNet can you please test it and let us know?

**Comment by Yehonal** [comment]
https://github.com/azerothcore/mod-cfbg/pull/17

This should be the fix, can someone test it?

**Comment by Winfidonarleyan** [comment]
Fix in #17
