### ISSUE TITLE
Join as a Group doesn't work [$100]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/mod-cfbg#12]
Joining as a group (party) does not work.

It would be nice if it can work and somehow try (but of course cannot guarantee) to maintain the original group members within the same team.

EDIT: there is a bounty on this issue. To consider it fixed, it MUST be properly tested and ALL corner cases should work. Including all different configurations enabled, for example:

```
CFBG.BalancedTeams = 1
CFBG.Include.Avg.Ilvl.Enable = 1
CFBG.Players.Count.In.Group = 2
CFBG.EvenTeams.Enabled = 1
CFBG.EvenTeams.MaxPlayersThreshold = 5
```

**Comment by BarbzYHOOL** [comment]
it can be done by editing the core, there is a check already. If we enable grouping even with different factions (for example when crossfaction conf enabled), then it would work fine, BUT what happens if they group and the server is lacking the CFBG module? crash? need to try first

i already suggested to winfi but he doesn't care xD

Don't know how we can encapsulate this change in the module otherwise but it's probably possible?

**Comment by mnclaras** [comment]
@BarbzYHOOL Can I know what change is needed to do in the core? I'm so interested in group joining 👍

**Comment by bronzato** [comment]
im very interested in group joining to, what we need to do ? i want ppl joing as group be on same team. i know a little of programming maybe i can help if you give me some insights

**Comment by FrancescoBorzi** [comment]
> im very interested in group joining to, what we need to do ? i want ppl joing as group be on same team. i know a little of programming maybe i can help if you give me some insights

@bronzato feel free to work on this! I can't give you further details because I haven't looked into this myself

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/mod-cfbg/commit/f01144fb60b077c460d043064ffc4fbd018e85c7

**Comment by Winfidonarleyan** [comment]
Need test f01144f

**Comment by Nano-GG** [comment]
Somebody else has tested https://github.com/azerothcore/mod-cfbg/commit/f01144fb60b077c460d043064ffc4fbd018e85c7 ¿¿??

**Comment by ilsonlojr** [comment]
@n4ndo its already done or WIP?

**Comment by ghost** [comment]
What is the status? It is done or not?

**Comment by Winfidonarleyan** [comment]
Wip

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan as you're busy with other things, I don't mind if @UltraNix picks this up. There is plenty of work to do for everyone anyway :) what do you say?

**Comment by ghost** [comment]
I'm not saying I'm not busy :)

**Comment by Winfidonarleyan** [comment]
@UltraNix You can try to fix it

**Comment by 55Honey** [comment]
Battlegrounds seem to be starting instantly when enough players are queued. We might want to add a small delay to the start, to be able to match more players of the same party into the same BG faction.
