### ISSUE TITLE
Original faction preference is not kept

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/mod-cfbg#13]
GIVEN THAT there are 3 Alliance players and 1 Horde player
AND they all queue a certain BG

EXPECTED BEHAVIOUR: the 1 Horde player should join as Horde, there is no reason to put him in the Alliance

CURRENT BEHAVIOUR: teams appear to be random, sometimes the 1 Horde player goes into the Alliance

More specifically: the original faction of the player should be kept. Moving a player to the other faction should happen **only when necessary**

**Comment by IceNet** [comment]
Confirmed

Happens from time to time.

**Comment by BarbzYHOOL** [comment]
low priority though xD

**Comment by FrancescoBorzi** [comment]
> low priority though xD

I'd say medium

**Comment by BarbzYHOOL** [comment]
it doesn't prevent players from playing at all unlike the other issues

**Comment by FrancescoBorzi** [comment]
true, but usually people play in a group of friends within the same faction and when they queue BG, the most likely want to be together and not against each other.

It's not a critical issue, I agree, but it's not trivial either IMHO.
