### ISSUE TITLE
Guild invite abusable [$15 awarded]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/mod-cfbg#19]
**GIVEN THAT** the Crossfaction-guild option is DISABLED
and I am an Ally character
**AND** I join BG
**AND** I'm playing as Horde player inside the BG
**THEN** during the BG, I can't join any Ally guild (wrong)
**AND** I can join Horde guilds (wrong)

**EXPECTED BEHAVIOUR**: I should only be able to join my own faction's guilds

**Comment by Shadofiend** [comment]
@Winfidonarleyan

Please fixed this is fun bad bug!

**Comment by Winfidonarleyan** [comment]
No time

**Comment by Winfidonarleyan** [comment]
Try after delete ace in my core

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5519
