### ISSUE TITLE
[SUGGESTION] RESET COOLDOWN IN BATTLEGROUND [$20 awarded]

### ISSUE THREAD

**Issue by DevMatheuss** [azerothcore/mod-cfbg#23]
My suggestion is to add an option in the crossfaction .conf, for each Battleground that enters resets the Cooldown of items and spells.

**Comment by BarbzYHOOL** [comment]
good idea!

can probably be copied from mod-duel-reset quite easily

**Comment by FrancescoBorzi** [comment]
we should be careful to only reset some spells cooldown, not all cooldowns (e.g. profession cooldowns should be excluded)

**Comment by robinsch** [comment]
@Winfidonarleyan @FrancescoBorzi  can this be be closed with PR: https://github.com/azerothcore/mod-cfbg/pull/60
being merged? so I can claim bounty.

**Comment by Winfidonarleyan** [comment]
Closed via pr #60
