### ISSUE TITLE
Config not being read 

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-cfbg#3]
the conf is not being read , confirmed on my server Debian 9 
By default the module is disabled

**Comment by BarbzYHOOL** [comment]
@Winfidonarleyan we need you!

**Comment by milestorme** [comment]
@Stoabrogga I made the issue here 

Will try fix this arvo

**Comment by Winfidonarleyan** [comment]
@milestorme You add config `.conf`?

**Comment by Winfidonarleyan** [comment]
In this module, the config works fine, there are no problems with the configuration if you configure it correctly

In travis - config work :/

**Comment by milestorme** [comment]
wow

**Comment by milestorme** [comment]
same console error here as on a live azerothcore config does not work fine its broken on Debian 9 and on ubuntu
Using World DB: ACDB 335.3 (dev)
1705
Initializing Scripts...
1706
Loading C++ scripts
1707
1708
Module config: Invalid or missing configuration file : /home/travis/build/milestorme/azerothcore-wotlk/env/dist/etc/CFBG.conf
1709
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
1710
Module config: Use default settings!
1711
1712
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
1713
Using DataDir /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/data/
1714
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
1715
1716
Loading Trinity strings...
1717
>> Loaded 1167 trinity strings in 2 ms
1718

**Comment by milestorme** [comment]
this is the azerothcore travis same error
`
Initializing Scripts...
1706
Loading C++ scripts
1707
1708
Module config: Invalid or missing configuration file : /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/etc/CFBG.conf
1709
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
1710
Module config: Use default settings!
1711
1712
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
1713
Using DataDir /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/data/
1714
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
1715
1716
Loading Trinity strings...
1717
>> Loaded 1167 trinity strings in 2 ms`

**Comment by milestorme** [comment]
and same error on a live server 
`AC>.reload conf
AC>Re-Loading config settings...

Module config: Invalid or missing configuration file : /home/wowtorn/rocketAC/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!

Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
AnticheatModule Loaded.

Module config: Invalid or missing configuration file : /home/wowtorn/rocketAC/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!`

**Comment by milestorme** [comment]
I have 25 modules working all confs working the only fail is this module it needs fixing

**Comment by milestorme** [comment]
https://cdn.discordapp.com/attachments/553105276023341107/614260769105903616/Untitled.png

**Comment by ghost** [comment]
As I wrote [here](https://github.com/azerothcore/mod-cfbg/pull/4#issuecomment-523197318) the Travis error is ok because Travis does not use a custom configuration file "CFBG.conf" for CFBG, it only uses the default "CFBG.conf.dist".

**Comment by ghost** [comment]
Ok, tested it on Ubuntu 16.04 and it works. Installed the module, then just started the server without "CFGB.conf", so this error is correct:
```
ERROR: Module config: Invalid or missing configuration file : /home/u1/azeroth-server/etc/CFBG.conf
ERROR: Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
ERROR: Module config: Use default settings!
```
After that stopped the server and copied the configuration file:
```
cp azeroth-server/etc/CFBG.conf.dist azeroth-server/etc/CFBG.conf
```
Started the server again and no errors anymore, so seems to work correctly.

**Comment by milestorme** [comment]
Guess I’ll just hack fix mine , since there’s no help 👌 no need for a conf anyway

**Comment by Winfidonarleyan** [comment]
oh my god :/

**Comment by Viste** [comment]
what the shit i read now?
must be 2 files conf and conf.dist look to the code.

**Comment by Viste** [comment]
what you talk about here? all works as should.
need both files conf and conf.dist plz read code.

**Comment by milestorme** [comment]
@Viste 

![](https://cdn.discordapp.com/attachments/553105276023341107/614260769105903616/Untitled.png)

**Comment by ghost** [comment]
@milestorme 
I'm sorry, but I can only test Ubuntu 16.04, don't have Debian 9 available. But as far as I understand cmake the file name is always determined the same way here, independently from the module:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/CMakeLists.txt#L195

So if the default file name is "CFBG.conf.dist" the cmake command "get_filename_component" with component "NAME_WE" will strip the file extension and the resulting name will be "CFBG.conf". If you have this file in the correct directory there's something wrong with it, e.g. it has the wrong file name (case-sensitive!) or wrong permissions.

**Comment by milestorme** [comment]
Yeah I know , I been helping others with all the same advice for other modules, and been fixing configs  to work on other modules, I understand I need both , I understand they need to have correct permissions, what I can’t understand is why it won’t read on my Debian server

**Comment by ghost** [comment]
I know that this is just wild guessing, but you could also check if your config file contains a space after the file name. This is not possible on Windows, but on Linux.

**Comment by Viste** [comment]
i guess debian is shit ) dont have this on CentOS and ArchLinux
@milestorme  can you show `ls -la` in your etc folder?

**Comment by ghost** [comment]
Just another guess: Debian 9 seems to support SELinux. Don't know if you use this, but I had problems with this some time ago on CentOS concerning file access.

@Viste
Debian is great, it's one of the most stable operating systems out there.

**Comment by Viste** [comment]
@Stoabrogga in past days yes for now its not true

**Comment by milestorme** [comment]
@Stoabrogga @viste Checked all that stuff , everything there is kosher. I’m very confused as to why i have 30+ working configs and one that doesn’t , hopefully someone else can repeat this , hate have 1 bad config out of over 30 , I looked over the script in this , the config is written different to what I’m used to . Not sure I can fix it myself

**Comment by milestorme** [comment]
why was this closed not resolved. re opening @BarbzYHOOL

**Comment by Winfidonarleyan** [comment]
**1. Without `CFBG.conf` and with `CFBG.conf.dist`**

![image](https://user-images.githubusercontent.com/18329778/63923375-ada60f80-ca70-11e9-9aa6-4c9cebf9df23.png)
![image](https://user-images.githubusercontent.com/18329778/63923395-b5fe4a80-ca70-11e9-86d3-62feee34d2af.png)

**2 With `CFBG.conf` and with `CFBG.conf.dist`**

![image](https://user-images.githubusercontent.com/18329778/63923552-efcf5100-ca70-11e9-915f-fa7aac39b7f2.png)
![image](https://user-images.githubusercontent.com/18329778/63923581-fb227c80-ca70-11e9-8d03-80817822b88b.png)

**Comment by milestorme** [comment]
Real helpful win , good job . Dick , I still have a broken config using defaults

**Comment by milestorme** [comment]
Close it again and it’s tge last time I contribute here

**Comment by Viste** [comment]
Don't forget to tell your mother.

**Comment by milestorme** [comment]
goodbye

**Comment by Viste** [comment]
@milestorme  Have a nice day.
I really didn't mean to offend you, but I don't know what to do to help you, I even raised the test server and checked if everything works and the config really works fine.

**Comment by milestorme** [comment]
yeah ya did, you guys are rude and un helpful , ive helped out new people while you snob them and be rude and nasty , this is an issue, but i dont care im out

**Comment by Viste** [comment]
Don't forget to tell your mother about this unfortunate injustice..

**Comment by milestorme** [comment]
thats it delete the comments you guys are just bullies

**Comment by Viste** [comment]
It's your choice, nobody has to help anyone. And accusing people of not helping anybody is super stupid.

**Comment by FrancescoBorzi** [comment]
No drama here. Issue reopened since the problem is still there.

Any help is welcome, other discussions are not.

**Comment by Viste** [comment]
What problem? do you have this problem? I don't, make a video at the end of the week.

**Comment by Yehonal** [comment]
Guys i want remember you that paths are handled different way on Windows and Linux.
Are you using standard way to include conf files? let me check

**Comment by Winfidonarleyan** [comment]
In win and in Debian 9 normal work

**Comment by xDevICCI** [comment]
in Ubuntu, CFBG / conf work fine !

**Comment by Winfidonarleyan** [comment]
@xDevICCI thanks for the feedback

**Comment by Winfidonarleyan** [comment]
@FrancescoBorzi Not problem :/ Config is correct working

**Comment by Yehonal** [comment]
Nice :)

**Comment by BarbzYHOOL** [comment]
we all know it works in ubuntu, but milestorme is on debian 9, dunno if that makes a difference

**Comment by Viste** [comment]
ubuntu(in core) = debian what difference ?? i dont have troubles on Arch

**Comment by FrancescoBorzi** [comment]
👍 👎 👍 👎 👍 👎 👍 👎 :relieved: :sweat_drops: :sweat_drops: :sweat_drops:
