### ISSUE TITLE
Bug: CFBG causes you to obtain achievements from both factions and can brick achievements. [$35 awarded]

### ISSUE THREAD

**Issue by ghost** [azerothcore/mod-cfbg#34]
I cannot get this because I have multiple achievments from both sides;

https://www.wowhead.com/achievement=1172/master-of-warsong-gulch#

https://www.wowhead.com/achievement=202/quick-cap

https://www.wowhead.com/achievement=1502/quick-cap

![WoWScrnShot_022021_170506](https://user-images.githubusercontent.com/61194190/108606403-cff0c300-73b1-11eb-817d-72bb177ad700.jpg)

**Comment by FrancescoBorzi** [comment]
@Helias can you have a look at this?
