### ISSUE TITLE
[Suggestion] Lessen system messages

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/mod-cfbg#38]
In the modules current state, there is one announcement per player which joins a battleground.
For example, if there are 4 characters queued and the bg pops open, there will be 4 announcements at once.
![image](https://user-images.githubusercontent.com/71938210/111707249-fd5f4e00-8843-11eb-963a-4c0fab8b6266.png)
I suggest a tiny delay, to limit the announcement per BG to the actual number of players.

Also, if a bg ends, many players will instantly rejoin the queue. If there are not enough players instantly to pop the next bg, the module should wait for - lets say for example - 5 seconds after the number of queued players changes.

**Comment by FrancescoBorzi** [comment]
done ;)
