### ISSUE TITLE
Config not being read 

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-cfbg#5]
Been an issue since modules release , I create modules and conf files to work on many modules, especially I fixed over 40 azerothcore module configs , this one errors , no changes everything default all mit credits left ,errors errors errors . Bad  module bad code

`AC>.reload conf
AC>Re-Loading config settings...

Module config: Invalid or missing configuration file : /home/wowtorn/rocketAC/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!

Will clear logs table of entries older than 1209600 seconds every 10 minutes.
WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
AnticheatModule Loaded.

Module config: Invalid or missing configuration file : /home/wowtorn/rocketAC/etc/CFBG.conf
Module config: Verify that the file exists and has '[worldserver]' written in the top of the file!
Module config: Use default settings!`

**Comment by BarbzYHOOL** [comment]
nop...
