### ISSUE TITLE
join bg bug!

### ISSUE THREAD

**Issue by darkenam** [azerothcore/mod-cfbg#74]
join bg  bug !

i changed in to battleground_template random bg min players team to 2vs2 but join bg buged!

for fix and join bg: if you use command: debug bg 1

os: windows

version: https://github.com/azerothcore/azerothcore-wotlk/commit/51aac38f5993064a015e548b6968a7b973158aee

**Comment by Winfidonarleyan** [comment]
After change rnd bg need change all bg

**Comment by darkenam** [comment]
all changed minplayersperteam to 2 but , dont work!

**Comment by Helias** [comment]
I didn't encounter this in the last period, so I am closing it. @darkenam if you still having this issue feel free to re-open this
