### ISSUE TITLE
CFBG balance

### ISSUE THREAD

**Issue by Helias** [azerothcore/mod-cfbg#78]
The level of the players inside a battleground **is not always balanced.**

### Scenario
4 characters
- lvl 10
- lvl 11
- 2x lvl 19

The first character lvl 10 join BG, one lvl 19 join BG -> result **lvl 10 vs lvl 19**

The other two join but the lvl 11 click on "Enter battle" for first -> in this case the CFBG see that the weak faction is the lvl 10 one, so it puts the lvl 11 with the lvl 10 and **later** it puts the lvl 19 with the other lvl 19

result -> 2x lvl 19 vs lvl 10,11

I reproduced this using the conf EvenTeams and LowLevelBalance enabled.

**Comment by ghost** [comment]
@Helias Show me your config about CFBG.

**Comment by Helias** [comment]
```
CFBG.Enable = 1
CFBG.BalancedTeams = 1
CFBG.Include.Avg.Ilvl.Enable = 1
CFBG.Players.Count.In.Group = 1
CFBG.EvenTeams.Enabled = 1
CFBG.EvenTeams.MaxPlayersThreshold = 7

# balance class
CFBG.BalancedTeams.Class.LowLevel = 1
CFBG.BalancedTeams.Class.MinLevel = 10
CFBG.BalancedTeams.Class.MaxLevel = 29
```
