### ISSUE TITLE
Help installing this

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/mod-cfbg#79]
Hey im rookie on modules but when I read the install instruction it felt easy so I tried but failed.

Anyway when I make a new build of acore with this mod in the module folder I get this error

Error	LNK2019	unresolved external symbol "void __cdecl Addmod_cfbg_masterScripts(void)" (?Addmod_cfbg_masterScripts@@YAXXZ) referenced in function "void __cdecl AddScripts(void)" (?AddScripts@@YAXXZ)	worldserver	E:\Server 2\1WoW Server WOTLK\Build\src\server\worldserver\scripts.lib(ScriptLoader.obj)	1	

I dont know how any of this really works, u know what I did wrong?

**Comment by Winfidonarleyan** [comment]
Please use git clone
