### ISSUE TITLE
BG balance system is bugged

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/mod-cfbg#99]
Running with:

```
CFBG.Include.Avg.Ilvl.Enable = 1
CFBG.BalancedTeams.Class.MaxLevel = 29
CFBG.Players.Count.In.Group = 1
CFBG.EvenTeams.MaxPlayersThreshold = 7
```

The balance system is sometimes not working properly as it creates teams that are completely wrong:

## Example scenario 1:

![unbalanced teams cfbg](https://cdn.discordapp.com/attachments/897504783194267748/941288728071143465/unknown.png)

4 players queue Warsong Gulch: 44, 44, 46, 49

**Expected result:** the system should create two teams of `49 and 44` vs `46 and 44`

**Actual result:** the system (sometimes) creates two teams of `49 and 46` vs `44 and 44`]

Completely wrong.

## Example scenario 2:

![unbalanced teams cfbg 2](https://cdn.discordapp.com/attachments/897504783194267748/941284141524189194/unknown.png)

4 players queue Warsong Gulch: 43, 44, 48, 49

**Expected result:** the system should create two teams of `49 and 43` vs `48 and 44`

**Actual result:** the system (sometimes) creates two teams of `49 and 48` vs `44 and 43`]

Completely wrong.

## Not reproducible

Both the scenario mentioned above happened for real. Unfortunately it is not easy to reproduce this issue but it keeps happening from time to time, it is not rare and it is extremely annoying. An investigation must be made in order to spot and fix the cause.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/mod-cfbg/issues/78
